openapi: 3.2.0
info:
  title: Lamini Completions API
  description: LLM inference and tuning for the enterprise. Factual LLMs. Classifier and embeddings. Deployed anywhere in 10 min.
  version: 1.13.6
security:
- APIKeyAuth: []
tags:
- name: Completions
  description: Run inference on your tuned models or base open source models.
paths:
  /v1/batch_completions:
    post:
      tags:
      - Completions
      summary: Make a batch inference request
      description: Kicks off batch inference for multiple prompts. Results can be retrieved using the job id returned on success.
      operationId: batch_completion_v1_batch_completions_post
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/BatchCompletionsPayload'
        required: true
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BatchInitialResponse'
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
      security:
      - API Key Auth: []
      parameters:
      - name: Authorization
        in: header
        required: true
        schema:
          type: string
        description: API key for authentication
  /v1/batch_completions/{id}/result:
    get:
      tags:
      - Completions
      summary: Get the inference results for a batch request
      description: Get the inference results for a batch request by passing in the ID of the batch request.
      operationId: batch_completion_result_v1_batch_completions__id__result_get
      parameters:
      - required: true
        schema:
          type: string
          title: Id
        name: id
        in: path
      - name: Authorization
        in: header
        required: true
        schema:
          type: string
        description: API key for authentication
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CompletionsWithFinishReasonResponse'
              example:
                outputs:
                - text: This is one inference output.
                - text: This is another output.
                finish_reason: stop
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
      security:
      - API Key Auth: []
  /v2/completions:
    post:
      tags:
      - Completions
      summary: Generate completions for prompts
      description: Generate an LLM inference response to a prompt, optionally with a specified JSON output structure, with a `finish_reason` field in the response indicating the end state for each inference request.
      operationId: completions_v2_completions_post
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CompletionsPayload'
        required: true
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CompletionsWithFinishReasonResponse'
              example:
                outputs:
                - text: This is one inference output.
                - text: This is another output.
                finish_reason: stop
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
      security:
      - API Key Auth: []
      parameters:
      - name: Authorization
        in: header
        required: true
        schema:
          type: string
        description: API key for authentication
  /v3/streaming_completions:
    post:
      tags:
      - Completions
      summary: Create a streaming inference completion
      description: Generate an LLM inference response to a prompt, optionally with a specified JSON output structure, with a `finish_reason` field in the response indicating the end state for each inference request.
      operationId: streaming_completions_v3_streaming_completions_post
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/V3StreamingCompletionsPayload'
        required: true
      responses:
        '200':
          description: The streaming inference completion.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BatchInitialResponse'
              example:
                id: 2af8bd94f5118480a0c7be525c26d1a9
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
      security:
      - API Key Auth: []
      parameters:
      - name: Authorization
        in: header
        required: true
        schema:
          type: string
        description: API key for authentication
  /v3/streaming_completions/{id}/result:
    get:
      tags:
      - Completions
      summary: Get the latest output of a streaming inference completion
      description: Get the result of a streaming completion by ID
      operationId: streaming_completion_result_v3_streaming_completions__id__result_get
      parameters:
      - required: true
        schema:
          type: string
          title: Id
        name: id
        in: path
      - name: Authorization
        in: header
        required: true
        schema:
          type: string
        description: API key for authentication
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CompletionsWithFinishReasonResponse'
              example:
                outputs:
                - text: This is one inference output.
                - text: This is another output.
                finish_reason: stop
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
      security:
      - API Key Auth: []
components:
  schemas:
    HTTPValidationError:
      properties:
        detail:
          items:
            $ref: '#/components/schemas/ValidationError'
          type: array
          title: Detail
      type: object
      title: HTTPValidationError
    ValidationError:
      properties:
        loc:
          items:
            anyOf:
            - type: string
            - type: integer
          type: array
          title: Location
        msg:
          type: string
          title: Message
        type:
          type: string
          title: Error Type
      type: object
      required:
      - loc
      - msg
      - type
      title: ValidationError
    CompletionsWithFinishReasonResponse:
      properties:
        outputs:
          items:
            additionalProperties:
              type: string
            type: object
          type: array
          title: Outputs
          description: The inference outputs for the given prompt(s).
        finish_reason:
          items:
            $ref: '#/components/schemas/FinishReason'
          type: array
          title: Finish Reason
          description: The final state for each inference request.
      type: object
      required:
      - outputs
      - finish_reason
      title: CompletionsWithFinishReasonResponse
    V3StreamingCompletionsPayload:
      properties:
        model_name:
          type: string
          title: Model Name
          description: The name of your base model.
          example: meta-llama/Llama-3.2-3B-Instruct
        prompt:
          type: string
          title: Prompt
          description: A single prompt for the model.
          example: What is the hottest day of the year?
        output_type:
          additionalProperties:
            anyOf:
            - type: string
            - items:
                type: integer
              type: array
            - items:
                type: string
              type: array
          type: object
          title: Output Type
          example:
            answer: str
          summary: Type schema of the output. Valid types are 'str', 'int', 'float', and 'bool'.
        max_new_tokens:
          type: integer
          title: Max New Tokens
          description: The maximum number of tokens to generate. Should be just large enough to accommodate the output you need - a lower value allows better pipeline execution speed and quality of service for batched requests.
          example: 500
      type: object
      required:
      - model_name
      - prompt
      title: V3StreamingCompletionsPayload
    BatchCompletionsPayload:
      properties:
        model_name:
          type: string
          title: Model Name
          description: The name of your base model.
          example: meta-llama/Llama-3.2-3B-Instruct
        prompt:
          items:
            type: string
          type: array
          title: Prompt
          description: Multiple prompts for the model, presented as a list of strings for batch processing.
          example:
          - What is the hottest day of the year?
          - What is the coldest day of the year?
        output_type:
          additionalProperties:
            anyOf:
            - type: string
            - items:
                type: integer
              type: array
            - items:
                type: string
              type: array
          type: object
          title: Output Type
          example:
            answer: str
          summary: Type schema of the output. Valid types are 'str', 'int', 'float', and 'bool'.
        max_new_tokens:
          type: integer
          title: Max New Tokens
          description: The maximum number of tokens to generate. Should be just large enough to accommodate the output you need - a lower value allows better pipeline execution speed and quality of service for batched requests.
          example: 500
        max_tokens:
          type: integer
          title: Max Tokens
        reservation_id:
          type: integer
          title: Reservation Id
      type: object
      required:
      - model_name
      - prompt
      title: BatchCompletionsPayload
    CompletionsPayload:
      properties:
        model_name:
          type: string
          title: Model Name
          description: The name of your base model.
          example: meta-llama/Llama-3.2-3B-Instruct
        prompt:
          anyOf:
          - type: string
          - items:
              type: string
            type: array
          title: Prompt
          description: The prompt for the model. Can be a single string or a list of strings for batch processing.
          example: What is the hottest day of the year?
        output_type:
          additionalProperties:
            anyOf:
            - type: string
            - items:
                type: integer
              type: array
            - items:
                type: string
              type: array
          type: object
          title: Output Type
          example:
            answer: str
          summary: Type schema of the output. Valid types are 'str', 'int', 'float', and 'bool'.
        max_tokens:
          type: integer
          title: Max Tokens
          description: The maximum number of tokens to generate.
        max_new_tokens:
          type: integer
          title: Max New Tokens
          description: The maximum number of tokens to generate. Should be just large enough to accommodate the output you need - a lower value allows better pipeline execution speed and quality of service for batched requests.
          example: 500
        reservation_id:
          type: integer
          title: Reservation Id
      type: object
      required:
      - model_name
      - prompt
      title: CompletionsPayload
    FinishReason:
      type: string
      enum:
      - stop
      - length
      - timeout
      title: FinishReason
      description: 'Indicates the ending state of the inference request.


        `stop`: The model completed the response with an EOS or equivalent token. This means the model finished generating the response.


        `length`: The response reached the maximum number of tokens as set by max_new_tokens or other token limit.


        `timeout`: The time taken to generate the response exceeded the configured Lamini Platform inference timeout. See [Performance](https://docs.lamini.ai/inference/performance/) for how to use this information to debug problems and improve performance.'
    BatchInitialResponse:
      properties:
        id:
          type: string
          title: Id
          description: The ID of the batch request.
          example: 2af8bd94f5118480a0c7be525c26d1a9
      type: object
      required:
      - id
      title: BatchInitialResponse
  securitySchemes:
    APIKeyAuth:
      type: apiKey
      in: header
      name: Authorization
      description: Enter your API token. Get your API key from http://localhost:5001/account
x-provenance:
  method: harvested
  publisher: Lamini
  source: https://docs.lamini.ai/openapi.json
  note: split by refine-openapis from the provider's own published document, verified by fetch (openapi/_original/*.fetch.json);
    stamped by stamp-openapi-provenance.py (roadmap#793)
